### PR TITLE
feat(client): use Ic icon on custom inspector/tab/command

### LINKED ISSUE #472: bug: vuex icon missing
Screenshot 2024-06-24 at 17 05 01

### PR DESCRIPTION
**Pull request by webfansplz**
Close #472

### CODE REVIEW

**Comment by alexzhang1030** [comment]
How about aligning with the behavior of `@unocss/preset-icons`? With the backgroundImage, we can easily use `font-size` to configure its width/height.

image

**Comment by reslear** [comment]
And why does this happen, is it because of treeshaking or should it be like this for offline first ?

**Comment by alexzhang1030** [comment]
> And why does this happen, is it because of treeshaking or should it be like this for offline first ?

To comply with Chromium Manifest V3 requirements, we bundled all the ic icons(for legacy devtools plugin api) together instead of loading them online. Manifest V3 does not support loading external resources.

**Comment by reslear** [comment]
ahhh got it. you should have specified that the icon pack names are like: `devtools-legacy` :)

**Comment by alexzhang1030** [comment]
@webfansplz updated, can you review it? Thanks

**Pull request merged**
