### PR TITLE
feat: group assets in duplicate paths between root and public by relativePath

### LINKED ISSUE #510: assets in duplicate paths between root and public will be divided into the same path in the assets tab
# description

assets in duplicate paths between root and public will be divided into the same path in the assets tab

I'm not sure if this behavior is expected.

image

reproduction URL: <https://stackblitz.com/edit/vitejs-vite-eonmde>

### PR DESCRIPTION
**Pull request by LoTwT**
# description

This PR is to close #510.

Todolist

- [x] add `relativePath` in `AssetInfo`
- [x] grid view
- [x] list view

### CODE REVIEW

**Comment by alexzhang1030** [comment]
https://vitejs.dev/config/shared-options.html#publicdir

How about read `publicDir` config

**Comment by LoTwT** [comment]
> https://vitejs.dev/config/shared-options.html#publicdir
> 
> Could you read the `publicDir` config to make it more robust?

Thank you for your advice. I will check it and optimize it later.

**Comment by alexzhang1030** [comment]
Can you provide a screenshot?

**Comment by LoTwT** [comment]
## steps

- nr dev
- nr play

https://github.com/user-attachments/assets/1be607cf-4c1d-4e92-a9f9-ed0616ba8cd9

### assets in root

image

### assets in public

image

### vite.svg

image

**Review by alexzhang1030 — APPROVED** [review]

**Pull request merged**
