### PR TITLE
fix(client): sync state between separate window with floating panel

### LINKED ISSUE #458: Seperate window cannot sync state with floating panel
I created a new vue project following the [Quick Start Guide](https://vuejs.org/guide/quick-start.html) using pnpm, js & vite.
When I opened a Chrome tab against http://localhost:5173/ , I found that the old devtools (chrome extension) is not working, instead, a new devtools shown as a float panel.
Here's the issue: I cancelled the tick on setting "Always show the floating panel" & closed the floating panel, and it never shown again, no matter I checked "Always show the floating panel" on or not ( in seperated tab of http://localhost:5173/__devtools__/)

image

image

I've tried refresh page / restart dev server / click "Reset Local Settings & State" button,  but still, the floating panel doesn't show.

But the keyboard shortcut shift + alt + d is still working, it can recover the floating panel button.
Use browser's "clear site data" can recover floating panel button too.

vue: 3.4.27
vite: 5.2.13
vite-plugin-vue-devtools: 7.2.1
Chrome: 125.0.6422.142

### PR DESCRIPTION
**Pull request by alexzhang1030**
should close #458, need test by @sxcooler, test on my local works properly.

Reproduction step:
1. open the page with the devtools floating panel
2. open a separate window
3. update settings on floating panel
4. go to the separate window, and storage is changed, but UI is not changed.

### CODE REVIEW

**Comment by sxcooler** [comment]
> should close #458, need test by @sxcooler, test on my local works properly.
> 
> Reproduction step:
> 
> 1. open the page with the devtools floating panel
> 2. open a separate window
> 3. update settings on floating panel
> 4. go to the separate window, and storage is changed, but UI is not changed.

Sorry, but how can I take part in testing?

**Comment by alexzhang1030** [comment]
## 1. clone source

You can use [gh CLI](https://cli.github.com)

image


Or clone my [repo](https://github.com/alexzhang1030/vue-devtools-next) and switch to `fix/client` branch.

## 2. build

```sh
pnpm i
pnpm build
```

## 3. link to your project

If you are using `pnpm`

```jsonc
// package.json
{
  "dependency": {
    //                                             <your-path-to-vite-package>
    "vite-plugin-vue-devtools": "../../../vue-devtools-next/packages/vite"
  }
}
```

**Comment by alexzhang1030** [comment]
> > ## 1. clone source
> > You can use [gh CLI](https://cli.github.com)
> 
> 谢谢指导，pnpm build的时候遇到以下两个错误：
> 
> image
> 
> 以及
> 
> image
> 
> 但我检查package/electron/dist目录，devtools.d.ts这个文件存在：
> 
> image
> 
> 如果强行把这个vite链接到我的项目，会出现devtools无法打开：
> 
> image
> 
> 一直停留在加载动画。
> 
> 我npmrc和pnpm config都已经加上了electron等的mirror 尝试过pnpm store prune无法解决
> 
> 我看你代码改动比较简单，原理上也说得通，你如果测试没有问题我可以先把原issue关闭。

😂, 可以等到 merge 了，这个 build error 的问题后面会追踪一下

**Review by webfansplz — APPROVED** [review]

**Comment by atilkan** [comment]
This comes with another issue. 
- From separate window
- Click select component button (Attachment 1)
- Select a component
- Floating panel appears, it should not based on my settings (Always hide), 
- And it doesn't disappear without clicking somewhere else, causing you to lose the selected component scope. 

Screenshot 2024-07-22 at 17 30 44

**Pull request merged**
