### PR TITLE
refactor(vite): load devtools resource

### LINKED ISSUE #518: File not found
I build a new monerepo by `@microsoft/rush` and add a new vue project that added `vite-plugin-vue-devtools`. But when I started this project, the plugin didn't work and gave me this exception: "GET http://localhost:5173/@id/virtual:vue-devtools-path:overlay.js net::ERR_ABORTED 404 (Not Found)" .

I have attached the code. Use `rushx dev` to start the vue project.
[common.zip](https://github.com/user-attachments/files/16172615/common.zip)

### PR DESCRIPTION
**Pull request by alexzhang1030**
I will dig into Vite and investigate why Vite can't resolve this.

Closes #518

### CODE REVIEW

**Comment by alexzhang1030** [comment]
The vite internal implementation of direct load assets by absolute path is [here](https://github.com/vitejs/vite/blob/564c8f45f5429bd149b441d7dca4f44347dedfb1/packages/vite/src/node/server/transformRequest.ts#L256-L261), it called a function [`isFileServingAllowed`](https://github.com/vitejs/vite/blob/564c8f45f5429bd149b441d7dca4f44347dedfb1/packages/vite/src/node/server/middlewares/static.ts#L210C17-L230) to check the ability. But there are some limitations when using this way to load devtools assets, like if we set `server.fs.strict` to `true`,  devtools assets cannot be loaded. Therefore, I believe this alternative method is better.

**Comment by webfansplz** [comment]
We need to test some use cases for platforms like Laravel and WXT. If it works on these platforms, we can push it forward.

**Comment by alexzhang1030** [comment]
> We need to test some use cases for platforms like Laravel and WXT. If it works on these platforms, we can push it forward.

I have tested it, it's working as usual.

**Comment by webfansplz** [comment]
> The vite internal implementation of direct load assets by absolute path is [here](https://github.com/vitejs/vite/blob/564c8f45f5429bd149b441d7dca4f44347dedfb1/packages/vite/src/node/server/transformRequest.ts#L256-L261), it called a function [`isFileServingAllowed`](https://github.com/vitejs/vite/blob/564c8f45f5429bd149b441d7dca4f44347dedfb1/packages/vite/src/node/server/middlewares/static.ts#L210C17-L230) to check the ability. But there are some limitations when using this way to load devtools assets, like if we set `server.fs.strict` to `true`, devtools assets cannot be loaded. Therefore, this alternative method is better. /cc @webfansplz

We can comment on the details in the codebase. like: https://github.com/webfansplz/vite-plugin-vue-inspector/blob/main/packages/core/src/index.ts#L184C14-L184C83

**Review by webfansplz — APPROVED** [review]

**Pull request merged**
