### PR TITLE
workflow: use turborepo to run script

### PR DESCRIPTION
**Pull request by alexzhang1030**
This PR adds [`turborepo`](https://turbo.build/repo) for task pipelineing and cache.

Additional messages:

- `./packages/xxx...` is two parts. `...` means dependencies, and `./` means relative path.
- ~~we run `build client` twice when executing `turbo build`, because the `electron` and `browser-extension` packages implicitly depend on the `client` package, so we should build the client before executing build packages.~~

### CODE REVIEW

**Comment by webfansplz** [comment]
Great work. Can we use dependsOn option to improve it?

**Comment by alexzhang1030** [comment]
> Great work. Can we use dependsOn option to improve it?

Yes, we can. But unfortunately, dependsOn cannot declare the dependencies.

Like:

```
{
  "foo#build": {
    "dependsOn": ["bar#build"]
  }
}
```

If the bar depends on `baz`, turbo cannot calculate the dependency graph by these.

**Comment by alexzhang1030** [comment]
I think something are messed, I will find it out later(maybe tomorrow :(

**Comment by alexzhang1030** [comment]
> Great work. Can we use dependsOn option to improve it?

After some investigation, ur right! We have to improve `dependsOn` on some packages.

CI passed, and this PR can merge at any time.

**Comment by webfansplz** [comment]
Awesome work, but we now seem to be having some issues with the cache not updating at build time.

Reproduction step: 1. change the client file, 2. run build shell, 3. run playground (work fine) 4. run the standalone app (work failed, the last cache was used)

**Pull request merged**
