### PR TITLE
feat(client): change inspect-component icon

### PR DESCRIPTION
**Pull request by maxirozay**
fix issue #294
Change overlay inspector icon to avoid having the same icon than the component inspector which has a different behavior.

### CODE REVIEW

**Comment by alexzhang1030** [comment]
This [one](https://icones.netlify.app/collection/all?s=inspect&icon=mingcute:inspect-line) looks nice.
image

**Comment by webfansplz** [comment]
Thanks for the PR, I prefer to swap the icon of 1 and 2.

image

**Comment by maxirozay** [comment]
I can do that in June unless someone wants to do it before.

**Comment by alexzhang1030** [comment]
Never mind, feel free to do it.

**Comment by alexzhang1030** [comment]
LGTM

**Review by alexzhang1030 — APPROVED** [review]

**Review by webfansplz — APPROVED** [review]

**Pull request merged**
